name: table-yolo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - default
dependencies:
  - python=3
  - numpy=1
  - llvm-openmp<16 # For CPU affinity pytorch issues (https://github.com/pytorch/pytorch/issues/102269)
  - pytorch
  - pytorch-cuda
  - cuda-toolkit
  - torchvision
  - opencv
  - matplotlib
  - scipy
  - pip=23
  - imagesize
  - pillow
  - natsort
  - ultralytics
  - tqdm
  - termcolor
  - tensorboard
  - distinctipy
  - shapely
